FROM python:3.12-slim

WORKDIR /app/GaX

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY GaX/ /app/GaX/
COPY frontend/ /app/frontend/

ENV PYTHONPATH=/app/GaX
