# Generated by Django 5.1.7 on 2026-09-11 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaxtronUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='hashed_password', max_length=255)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(db_column='is_superadmin', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WalletAuthNonce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet_auth_nonces',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=255)),
                ('key_prefix', models.CharField(max_length=12)),
                ('name', models.CharField(default='default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('chain', models.CharField(db_index=True, default='ETH', max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('wallet_address', models.CharField(db_index=True, max_length=128)),
                ('callback_url', models.TextField()),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=72, null=True, unique=True)),
                ('event_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('chain', models.CharField(default='ETH', max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('from_address', models.CharField(max_length=128)),
                ('to_address', models.CharField(max_length=128)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchants.payment')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=128, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('chain', models.CharField(default='ETH', max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='merchants.payment')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('callback_url', models.TextField()),
                ('payload', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='merchants.payment')),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
